spring:
   profiles.active: dev

logging:
  level:
    com.tzcpa.mapper: DEBUG
    org.springframework: DEBUG

#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
conf:
  value:
    machineCode: 1
es:
  host: 127.0.0.1
  port: 9200
  scheme: http
