server:
  port: 8090
  tomcat.max-threads: 30
  tomcat.uri-encoding: UTF-8
#  servlet:
#    context-path: /ks



debug: true

#logging:
#    level:
#      root: warn
#      com.qdp.demo.mapper: trace


spring:
  application:
    name: koma_case
  datasource:
    url: jdbc:h2:~/koma_case
    driver-class-name: org.h2.Driver
    username: koma
    password: 123456
  jackson:
    default-property-inclusion: ALWAYS
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/**,classpath:/public/
#设置cglib代理模式，防止非接口代理出错
  aop:
    proxy-target-class: true



web:
  upload-path: D:/images/


